### ISSUE TITLE
'jirkavrba.subway-surfers' as it is not compatible with VS Code '1.75.1

### ISSUE THREAD

**Issue by Itxyy** [jirkavrba/vscode-subway-surfers#4] opened 2023-04-27 12:06 UTC
I have issues installing the extension:
Unable to install extension 'jirkavrba.subway-surfers' as it is not compatible with VS Code '1.75.1'.

I realized this extension is set for VSCode ^1.76.0

To workaround this I modified package.json to support ^1.75.0, not sure if my VScode is outdated and doesn't want to update.

**Comment by jirkavrba** [comment] 2023-04-27 13:28
The current version is 1.77, I think this was caused by 1.76 being the latest version at the time of making this extension.

I will look into the support of all required features and lower the required version as much as possible

**Comment by jirkavrba** [comment] 2023-05-01 14:27
Resolved in v1.1.1

**Closed by jirkavrba** 2023-05-01 14:27 UTC
